// src/views/Gamemode.vue
<template>
  <div class="h-[93vh] bg-main">
    <div class="flex h-[80vh] flex-col items-center justify-center">

      <ButtonGamemode text="Classic" link="/play/classic" @link-click="chooseGamemode" />

      <ButtonGamemode text="Guess" link="/play/guess" @link-click="chooseGamemode" />

    </div>
  </div>
</template>

<script>
import ButtonGamemode from '../components/Button/ButtonGamemode.vue';

export default {
  components: {
    ButtonGamemode,
  },
  methods: {
    chooseGamemode(mode) {
      this.$router.push(mode);
    },
  },
};
</script>

// src/views/Gamemode.tsx
import ButtonGamemode from '../components/Button/ButtonGamemode.vue';

export default function Gamemode() {
  return (
    <div className={'h-[90vh] bg-main'}>
      <div className={'flex h-[80vh] flex-col items-center justify-center'}>
        <ButtonGamemode text={'Classic'} link={'ok'} />
        <ButtonGamemode text={'Guess'} link={'ok'} />
      </div>
    </div>
  );
}
